---
title: "data_analysis"
author: "Kunlei He"
date: "2024-02-20"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    toc_collapse: true
    number_sections: true
    df_print: paged
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

# Load library
```{r}
library(dplyr)
library(ggplot2)
library(lme4)
```

# Load data
```{r}
df_Master = read.csv("clean_data/master.csv")
```

# 2. Analysis
## Descriptive by episode
### Visual
```{r}

boxColors = c("#FF9843", "#7AA874", "#6096B4", "#D2D4D6")
conditionLabels = c("Interactive", "Human", "Pseudo-interactive", "Non-interactive")

# POST

# check post 117 by condition
df_Master$condition117 = factor(df_Master$condition117, levels = c("interactive", "no", "semi", "human"))
ggplot(df_Master, aes(x=condition117, y=p117_total_score, fill=condition117)) +
  geom_violin(width=0.8, adjust= 0.8, show.legend = FALSE) +
  geom_boxplot(width=0.1, fill="white") +
    stat_summary(fun.y=mean, geom="point", shape=20, size=3, color="#BF3131", fill="#BF3131") +
  labs(title="Post Test Score for Video 1 (Molting) by Condition",
       x="",
       y="Post Test Total Score") +
  scale_fill_manual(values=boxColors, labels=conditionLabels) + 
  scale_x_discrete(labels=conditionLabels) +
  theme_bw() +
  theme(text=element_text(size = 14),
        axis.text.x = element_text(color="black"),
        plot.title = element_text(hjust = 0.5))

# check post 109 by condition
ggplot(df_Master, aes(x=condition109, y=p109_total_score, fill=condition109)) +
  geom_violin(width=0.8, adjust= 0.8, show.legend = FALSE) +
  geom_boxplot(width=0.1, fill="white") +
  stat_summary(fun.y=mean, geom="point", shape=20, size=3, color="#BF3131", fill="#BF3131") +
  labs(title="Post Test Score for Video 2 (Aerodymanics) by Condition",
       x="",
       y="Post Test Total Score") +
  scale_fill_manual(values=boxColors, labels=conditionLabels) + 
  scale_x_discrete(labels=conditionLabels) +
  theme_bw() +
  theme(text=element_text(size = 14),
        axis.text.x = element_text(color="black"),
        plot.title = element_text(hjust = 0.5))

# check post 101 by condition
ggplot(df_Master, aes(x=condition101, y=p101_total_score, fill=condition101)) +
  geom_violin(width=0.8, adjust= 0.8, show.legend = FALSE) +
  geom_boxplot(width=0.1, fill="white") +
    stat_summary(fun.y=mean, geom="point", shape=20, size=3, color="#BF3131", fill="#BF3131") +
  labs(title="Post Test Score for Video 3 (Viscosity) by Condition",
       x="",
       y="Post Test Total Score") +
  scale_fill_manual(values=boxColors, labels=conditionLabels) + 
  scale_x_discrete(labels=conditionLabels) +
  theme_bw() +
  theme(text=element_text(size = 14),
        axis.text.x = element_text(color="black"),
        plot.title = element_text(hjust = 0.5))

# DELAYED
# check post 117 by condition
ggplot(df_Master, aes(x=condition117, y=d117_total_score, fill=condition117)) +
  geom_violin(width=0.8, adjust= 0.8, show.legend = FALSE) +
  geom_boxplot(width=0.1, fill="white") +
    stat_summary(fun.y=mean, geom="point", shape=20, size=3, color="#BF3131", fill="#BF3131") +
  labs(title="First Delayed Post Test Score (Episode 117) by Condition",
       x="",
       y="Delayed Post Test Total Score") +
  scale_fill_manual(values=boxColors, labels=conditionLabels) + 
  scale_x_discrete(labels=conditionLabels) +
  theme_bw() +
  theme(text=element_text(size = 14),
        axis.text.x = element_text(color="black"),
        plot.title = element_text(hjust = 0.5))


# check post 109 by condition
ggplot(df_Master, aes(x=condition109, y=d109_total_score, fill=condition109)) +
  geom_violin(width=0.8, adjust= 0.8, show.legend = FALSE) +
  geom_boxplot(width=0.1, fill="white") +
    stat_summary(fun.y=mean, geom="point", shape=20, size=3, color="#BF3131", fill="#BF3131") +
  labs(title="Second Delayed Post Test Score (Episode 109) by Condition",
       x="",
       y="Delayed Post Test Total Score") +
  scale_fill_manual(values=boxColors, labels=conditionLabels) + 
  scale_x_discrete(labels=conditionLabels) +
  theme_bw() +
  theme(text=element_text(size = 14),
        axis.text.x = element_text(color="black"),
        plot.title = element_text(hjust = 0.5))

```

### Summary Stats by episode
```{r}
summary_Post117 = aggregate(data=df_Master, p117_total_score ~ condition117, FUN = summary)
summary_Post109 = aggregate(data=df_Master, p109_total_score ~ condition109, FUN = summary)
summary_Post101 = aggregate(data=df_Master, p101_total_score ~ condition101, FUN = summary)

summary_Delayed117 = aggregate(data=df_Master, d117_total_score ~ condition117, FUN = summary)
summary_Delayed109 = aggregate(data=df_Master, d109_total_score ~ condition109, FUN = summary)

```


## Long form data
```{r}
# generate proportional measures


# retrieve columns of interest
df_Long = df_Master %>% dplyr::select(id, group, age, gender, ethnicity, eng_prof, condition117, condition109, condition101, p117_total_score, d117_total_score, p109_total_score, d109_total_score, p101_total_score)

# pivot longer for condition for each episode
df_Long = df_Long %>%
  pivot_longer(
    cols = starts_with("condition"),
    names_to = "episode",
    values_to = "condition",
    names_prefix = "condition"
  ) 

# create a column for post-test score
df_Long = df_Long %>%
  mutate(post_total_score = case_when(
    episode == "117" ~ p117_total_score,
    episode == "109" ~ p109_total_score,
    episode == "101" ~ p101_total_score,
    TRUE ~ NA_real_  # This line handles cases where episode does not match any of the specified, assigning NA
  ))

# create a column for delayed score
df_Long = df_Long %>%
  mutate(delayed_total_score = case_when(
    episode == "117" ~ d117_total_score,
    episode == "109" ~ d109_total_score,
    TRUE ~ NA_real_  # This line handles cases where episode does not match any of the specified, assigning NA
  ))

# remove d and p score
df_Long = subset(df_Long, select = -c(p117_total_score, d117_total_score, p109_total_score, d109_total_score, p101_total_score))
```

### Descriptive Stats by condition
```{r}
## generate proportional scores
df_Long$post_score_prop = ifelse(df_Long$episode==117, df_Long$post_total_score/26, 
                                 ifelse(df_Long$episode==109, df_Long$post_total_score/14,
                                        ifelse(df_Long$episode==101, df_Long$post_total_score/22, NA)))

df_Long$delayed_score_prop = ifelse(df_Long$episode==117, df_Long$delayed_total_score/26, 
                                 ifelse(df_Long$episode==109, df_Long$delayed_total_score/14,
                                        ifelse(df_Long$episode==101, df_Long$delayed_total_score/22, NA)))

summary_PostPropCondition = aggregate(data=df_Long, post_score_prop ~ condition, FUN=summary)
summary_DelayedPropCondition = aggregate(data=df_Long, delayed_score_prop ~ condition, FUN=summary)
```

Visualize
```{r}
boxColors = c("#FF9843", "#7AA874", "#6096B4", "#D2D4D6")
conditionLabels = c("Interactive", "Human", "Pseudo-interactive", "Non-interactive")

# POST
df_Long$condition = factor(df_Long$condition, levels = c("interactive", "no", "semi", "human"))
ggplot(df_Long, aes(x=condition, y=post_score_prop, fill=condition)) +
  geom_violin(width=0.8, adjust= 0.8, show.legend = FALSE) +
  geom_boxplot(width=0.1, fill="white") +
  stat_summary(fun.y=mean, geom="point", shape=20, size=3, color="#BF3131", fill="#BF3131") +
  # stat_summary(fun.y = mean, geom = "crossbar", width = 0.1, color = "red", size=1.2, fatten = 0, aes(ymin = ..y.., ymax = ..y..), show.legend = F) +
  labs(title="Post-test Performance by Condition",
       x="",
       y="Post-test Accuracy Rate") +
  scale_fill_manual(values=boxColors, labels=conditionLabels) + 
  scale_x_discrete(labels=conditionLabels) +
  #scale_y_continuous(limits = c(0, 25), oob = scales::rescale_none) +
  theme_bw() +
  theme(text=element_text(size = 14),
        axis.text.x = element_text(color="black"),
        plot.title = element_text(hjust = 0.5))

# DELAYED
df_Long$condition = factor(df_Long$condition, levels = c("interactive", "no", "semi", "human"))
ggplot(df_Long, aes(x=condition, y=delayed_score_prop, fill=condition)) +
  geom_violin(width=0.8, adjust= 0.8, show.legend = FALSE) +
  geom_boxplot(width=0.1, fill="white") +
  stat_summary(fun.y=mean, geom="point", shape=20, size=3, color="#BF3131", fill="#BF3131") +
  scale_y_continuous(limits = c(0, 1), oob = scales::rescale_none) +
  labs(title="Delayed Post-test Performance by Condition",
       x="",
       y="Delayed Post-test Accuracy Rate") +
  scale_fill_manual(values=boxColors, labels=conditionLabels) + 
  scale_x_discrete(labels=conditionLabels) +
  theme_bw() +
  theme(text=element_text(size = 14),
        axis.text.x = element_text(color="black"),
        plot.title = element_text(hjust = 0.5))

```



### Mixed-effects model
```{r}
fit <- lmer(post_score_prop ~ condition + (1|id) + (1|episode) + age + eng_prof + eng_prof*condition, data = df_Long)
summary(fit)
```

<!-- Generate aggregate score for interactive -->
<!-- ```{r} -->
<!-- df_Agg = df_Analysis %>% group_by(id, condition) %>%  -->
<!--   summarise(agg_post_score = mean(post_total_score, na.rm=T), -->
<!--             agg_delayed_score = mean(delayed_total_score, na.rm=T), -->
<!--             .groups="drop") -->

<!-- # check dup rows -->
<!-- dupRows <- df_Agg %>% -->
<!--   group_by(id, condition) %>% -->
<!--   filter(n() > 1) %>% -->
<!--   ungroup() -->

<!-- print(dupRows) -->

<!-- # merge covariates -->
<!-- df_Agg = merge(df_Agg, df_Tracker[, c("id", "age", "gender", "ethnicity", "eng_prof")], by=c("id"), all.x=T) -->


<!-- ## aggregate by condition -->
<!-- df_Analysis %>% group_by(id, condition, age, gender, ethnicity, eng_prof, ) -->
<!-- ``` -->


#### ANOVA
```{r}
# ANOVA
model = aov(data=df_Agg, agg_post_score ~ condition + age + gender + ethnicity + eng_prof)
summary(model)

TukeyHSD(model, which = "condition")
```

#### Regression
```{r}
df_Agg$condition = factor(df_Agg$condition)
df_Agg$condition <- relevel(df_Agg$condition, ref = "interactive")
model = lm(data = df_Agg, scale(agg_post_score) ~ condition + age + gender + ethnicity)
summary(model)
```

## Remove five outliers from interactive
```{r}
# remove 5 outliers from interactive
df_Interactive <- df_Agg[df_Agg$condition == "interactive", ]
df_InteractiveOrdered <- df_Interactive[order(df_Interactive$agg_post_score), ]

# Step 3: Identify the rows of the last five agg_post_score values
rows_to_remove <- head(df_InteractiveOrdered, 5)

# Step 4: Remove these rows from the original dataframe
df_AggFiltered <- df_Agg[!rownames(df_Agg) %in% rownames(rows_to_remove), ]

```

Visual
```{r}
df_AggFiltered$condition = factor(df_AggFiltered$condition, levels=c("interactive", "semi", "no", "human"))

ggplot(df_AggFiltered, aes(x=condition, y=scale(agg_post_score), fill=condition)) +
  geom_boxplot() +
  labs(title="Boxplot of Post by Condition",
       x="Condition",
       y="Post Total Score") +
  theme_minimal()


ggplot(df_AggFiltered, aes(x=condition, y=scale(agg_delayed_score), fill=condition)) +
  geom_boxplot() +
  labs(title="Boxplot of Delayed Post by Condition",
       x="Condition",
       y="Post Total Score") +
  theme_minimal()

```

### ANOVA
```{r}
# post
model = aov(data=df_AggFiltered, agg_post_score ~ condition + age + gender + ethnicity)
summary(model)

TukeyHSD(model, which = "condition")

# delayed
model = aov(data=df_AggFiltered, agg_delayed_score ~ condition + age + gender + ethnicity + eng_prof)
summary(model)

TukeyHSD(model, which = "condition")

```

## Regression
```{r}
# post
df_AggFiltered$condition = factor(df_AggFiltered$condition)
df_AggFiltered$condition <- relevel(df_AggFiltered$condition, ref = "interactive")
model = lm(data = df_AggFiltered, scale(agg_post_score) ~ condition + age + gender + ethnicity + eng_prof)
summary(model)

# delayex
df_AggFiltered$condition = factor(df_AggFiltered$condition)
df_AggFiltered$condition <- relevel(df_AggFiltered$condition, ref = "interactive")
model = lm(data = df_AggFiltered, scale(agg_delayed_score) ~ condition + age + gender + ethnicity + eng_prof)
summary(model)
```

```{r}
df_Analysis$condition = factor(df_Analysis$condition, levels = c("interactive", "semi", "no", "human"))
model <- lmer(scale(post_total_score) ~ condition + gender + age + ethnicity + eng_prof + (1|id), data = df_Analysis)
summary(model)
```

```{r}
df_test = df_Master %>% dplyr::select(id, age, gender, ethnicity, eng_prof, condition117, condition109, condition101, p117_total_score, p109_total_score, p101_total_score)
df_test$condition117 = factor(df_test$condition117, levels=c("interactive", "semi", "no", "human"))
df_test$condition109 = factor(df_test$condition109, levels=c("interactive", "semi", "no", "human"))
df_test$condition101 = factor(df_test$condition101, levels=c("interactive", "semi", "no", "human"))

model = lm(data=df_test, p117_total_score ~ condition117 + age + gender + ethnicity + eng_prof)
summary(model)

model = lm(data=df_test, p109_total_score ~ condition109 + age + gender + ethnicity + eng_prof)
summary(model)

model = lm(data=df_test, p101_total_score ~ condition101 + age + gender + ethnicity + eng_prof)
summary(model)
```
