---
title: "merge-109-manual"
author: "Kunlei He"
date: "2025-02-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
```

```{r}
# load manual delayed and post-test scores for 109
df_Post109Manual <- read.csv("raw_data/post_109_manual.csv")
df_Delayed109Manual <- read.csv("raw_data/delayed_109_manual.csv")
```

```{r}
# Load manual scores for q5b for immediate and delayed post test
file_path <- "raw_data/109_q5b.xlsx"
sheet_names <- excel_sheets(file_path)
for (s in sheet_names) {
  assign(s, read_excel(file_path, sheet = s))
}


# Load manual scores for q6b and q7b for immediate and delayed post test
file_path <- "raw_data/109_q6b_q7b.xlsx"
sheet_names <- excel_sheets(file_path)
for (s in sheet_names) {
  assign(s, read_excel(file_path, sheet = s))
}
```

```{r}
# merge 'p109_q5b_cr'to df_Post109Manual by id
df_Post109Manual <- df_Post109Manual %>%
  left_join(p109_q5b_cr[c("id", "p109_q5b_cr_score")], by = "id")

# merge 'p109_q6b_cr'to df_Post109Manual by id
df_Post109Manual <- df_Post109Manual %>%
  left_join(p109_q6b_cr[c("id", "p109_q6b_cr_score")], by = "id")

# merge 'p109_q7b_cr'to df_Post109Manual by id
df_Post109Manual <- df_Post109Manual %>%
  left_join(p109_q7b_cr[c("id", "p109_q7b_cr_score")], by = "id")
```

```{r}
# merge 'd109_q5b_cr'to df_Delayed109Manual by id
df_Delayed109Manual <- df_Delayed109Manual %>%
  left_join(d109_q5b_cr[c("id", "d109_q5b_cr_score")], by = "id")

# merge 'd109_q6b_cr'to df_Delayed109Manual by id
df_Delayed109Manual <- df_Delayed109Manual %>%
  left_join(d109_q6b_cr[c("id", "d109_q6b_cr_score")], by = "id")

# merge 'd109_q7b_cr'to df_Delayed109Manual by id
df_Delayed109Manual <- df_Delayed109Manual %>%
  left_join(d109_q7b_cr[c("id", "d109_q7b_cr_score")], by = "id")
```

```{r}
# write df_Post109Manual and df_Delayed109Manual to csv
write.csv(df_Post109Manual, "raw_data/post_109_manual.csv", row.names = FALSE)
write.csv(df_Delayed109Manual, "raw_data/delayed_109_manual.csv", row.names = FALSE)
```

